image: golang:latest

before_script:
  - export GOPATH=${CI_PROJECT_DIR}/.cache
  - export GOARCH=386
  - export OSS="windows linux"
  - apt-get update -qq && apt-get -y -qq install jq xxd

stages:
  - release

release:
  stage: release
  script:
    - go get ssh-engine
    - for os in ${OSS}; do GOOS=$os GOARCH=${GOARCH} make cross; done
    - apt-get -qq -y install curl
    - /bin/sh makerelease.sh SshEngine
  artifacts:
    paths:
      - SshEngine_*
  only:
    - tags
